# Generated by Django 3.2.5 on 2021-09-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('edition', models.IntegerField(default='1000')),
                ('publication', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=10)),
            ],
        ),
    ]
